export default [
  "Nintendo",
  "Sony Interactive Entertainment",
  "Microsoft Studios",
  "Electronic Arts (EA)",
  "Activision Blizzard",
  "Ubisoft",
  "Bethesda Game Studios",
  "Rockstar Games",
  "Valve Corporation",
  "Square Enix",
  "Epic Games",
  "CD Projekt Red",
  "Naughty Dog",
  "Capcom",
  "Sega",
  "Bandai Namco Entertainment",
  "Mojang Studios",
  "Riot Games",
  "2K Games",
  "FromSoftware",
  "BioWare",
  "Insomniac Games",
  "Bungie",
  "Konami",
  "Gearbox Software",
  "PlatinumGames",
  "Telltale Games",
  "Remedy Entertainment",
  "Firaxis Games",
  "Rare Ltd.",
];
