export default [
  "Action",
  "Adventure",
  "Role-playing (RPG)",
  "First-person shooter (FPS)",
  "Sports",
  "Racing",
  "Strategy",
  "Simulation",
  "Puzzle",
  "Fighting",
  "Sandbox",
  "Platformer",
  "Horror",
  "Stealth",
  "Survival",
  "Open world",
  "MMO (Massively Multiplayer Online)",
  "Roguelike",
  "Tactical shooter",
  "Metroidvania",
  "Point-and-click",
  "Tower defense",
  "Card and board games",
  "Educational",
  "Party and minigames",
  "Music and rhythm",
  "Visual novel",
  "Idle games",
  "MOBA (Multiplayer Online Battle Arena)",
  "Battle Royale",
  "Two-player Games",
  "Games for Kids",
];
